python3 build_medicalgraph.py
Traceback (most recent call last):
  File "build_medicalgraph.py", line 269, in <module>
    handler = MedicalGraph()
  File "build_medicalgraph.py", line 19, in __init__
    password="123456")
  File "/usr/local/lib/python3.6/site-packages/py2neo/database.py", line 288, in __init__
    self.service = GraphService(profile, **settings)
  File "/usr/local/lib/python3.6/site-packages/py2neo/database.py", line 115, in __init__
    profile = ServiceProfile(profile, **settings)
  File "/usr/local/lib/python3.6/site-packages/py2neo/__init__.py", line 475, in __init__
    super(ServiceProfile, self).__init__(profile, **settings)
  File "/usr/local/lib/python3.6/site-packages/py2neo/__init__.py", line 190, in __init__
    self._apply_settings(**settings)
  File "/usr/local/lib/python3.6/site-packages/py2neo/__init__.py", line 512, in _apply_settings
    auth, user, password, **other)
  File "/usr/local/lib/python3.6/site-packages/py2neo/__init__.py", line 293, in _apply_settings
    raise ValueError("The following settings are not supported: %r" % other)
ValueError: The following settings are not supported: {'http_port': 7474}

pip3 install py2neo==
Collecting py2neo==
  Could not find a version that satisfies the requirement py2neo== (from versions: 4.0.0, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.2.0, 4.3.0, 2020.0.0, 2020.1.0, 2020.1.1, 2021.0.0, 2021.0.1, 2021.1.0, 2021.1.1, 2021.1.2, 2021.1.3, 2021.1.4, 2021.1.5, 2021.2.0, 2021.2.1, 2021.2.2, 2021.2.3)
No matching distribution found for py2neo==

python3 chat_graph.py
python3: can't open file 'chat_graph.py': [Errno 2] No such file or directory
[bj@fe1 QASystemOnMedicalKG]$ python3 chatbot_graph.py
Traceback (most recent call last):
  File "chatbot_graph.py", line 7, in <module>
    from question_classifier import *
  File "/home/bj/git/QASystemOnMedicalKG/question_classifier.py", line 8, in <module>
    import ahocorasick
ModuleNotFoundError: No module named 'ahocorasick'